# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainform.ui'
#
# Created: Sun May 10 10:39:52 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(1024, 768)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        mainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        mainWindow.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(mainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.mainSplitter = QtGui.QSplitter(self.centralWidget)
        self.mainSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.mainSplitter.setObjectName("mainSplitter")
        self.verticalLayoutWidget = QtGui.QWidget(self.mainSplitter)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tableView = QtGui.QTableView(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.tableView.setFont(font)
        self.tableView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        self.layoutWidget = QtGui.QWidget(self.mainSplitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dockWidget = QtGui.QDockWidget(self.layoutWidget)
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.dateEdit_From = QtGui.QDateEdit(self.dockWidgetContents)
        self.dateEdit_From.setCalendarPopup(True)
        self.dateEdit_From.setObjectName("dateEdit_From")
        self.gridLayout.addWidget(self.dateEdit_From, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.dockWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.dateEdit_To = QtGui.QDateEdit(self.dockWidgetContents)
        self.dateEdit_To.setCalendarPopup(True)
        self.dateEdit_To.setObjectName("dateEdit_To")
        self.gridLayout.addWidget(self.dateEdit_To, 0, 3, 1, 1)
        self.label_3 = QtGui.QLabel(self.dockWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.comboBox_SearchName = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBox_SearchName.setEditable(True)
        self.comboBox_SearchName.setObjectName("comboBox_SearchName")
        self.gridLayout.addWidget(self.comboBox_SearchName, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.dockWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.comboBox_SearchCategory = QtGui.QComboBox(self.dockWidgetContents)
        self.comboBox_SearchCategory.setEditable(True)
        self.comboBox_SearchCategory.setObjectName("comboBox_SearchCategory")
        self.gridLayout.addWidget(self.comboBox_SearchCategory, 1, 3, 1, 1)
        self.label_5 = QtGui.QLabel(self.dockWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_OutCome = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_OutCome.setFont(font)
        self.label_OutCome.setObjectName("label_OutCome")
        self.gridLayout.addWidget(self.label_OutCome, 2, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.dockWidgetContents)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.label_InCome = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_InCome.setFont(font)
        self.label_InCome.setObjectName("label_InCome")
        self.gridLayout.addWidget(self.label_InCome, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.dockWidgetContents)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_TotalLeft = QtGui.QLabel(self.dockWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_TotalLeft.setFont(font)
        self.label_TotalLeft.setObjectName("label_TotalLeft")
        self.gridLayout.addWidget(self.label_TotalLeft, 4, 1, 1, 1)
        self.dockWidget.setWidget(self.dockWidgetContents)
        self.verticalLayout_2.addWidget(self.dockWidget)
        self.dockWidget_2 = QtGui.QDockWidget(self.layoutWidget)
        self.dockWidget_2.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_2.setObjectName("dockWidget_2")
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName("dockWidgetContents_2")
        self.gridLayout_2 = QtGui.QGridLayout(self.dockWidgetContents_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.comboBox_Name = QtGui.QComboBox(self.dockWidgetContents_2)
        self.comboBox_Name.setEditable(True)
        self.comboBox_Name.setObjectName("comboBox_Name")
        self.gridLayout_2.addWidget(self.comboBox_Name, 0, 1, 1, 1)
        self.label_Date = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_Date.setObjectName("label_Date")
        self.gridLayout_2.addWidget(self.label_Date, 2, 2, 1, 1)
        self.dateEdit_Date = QtGui.QDateEdit(self.dockWidgetContents_2)
        self.dateEdit_Date.setCalendarPopup(True)
        self.dateEdit_Date.setObjectName("dateEdit_Date")
        self.gridLayout_2.addWidget(self.dateEdit_Date, 2, 3, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(self.dockWidgetContents_2)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 3, 0, 1, 4)
        self.label_Number = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_Number.setObjectName("label_Number")
        self.gridLayout_2.addWidget(self.label_Number, 1, 0, 1, 1)
        self.doubleSpinBox_OutCome = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.doubleSpinBox_OutCome.setMinimum(-99999999.99)
        self.doubleSpinBox_OutCome.setMaximum(99999999.99)
        self.doubleSpinBox_OutCome.setObjectName("doubleSpinBox_OutCome")
        self.gridLayout_2.addWidget(self.doubleSpinBox_OutCome, 1, 1, 1, 1)
        self.label_UnitPrice = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_UnitPrice.setObjectName("label_UnitPrice")
        self.gridLayout_2.addWidget(self.label_UnitPrice, 1, 2, 1, 1)
        self.doubleSpinBox_InCome = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.doubleSpinBox_InCome.setMinimum(-99999999.99)
        self.doubleSpinBox_InCome.setMaximum(99999999.99)
        self.doubleSpinBox_InCome.setObjectName("doubleSpinBox_InCome")
        self.gridLayout_2.addWidget(self.doubleSpinBox_InCome, 1, 3, 1, 1)
        self.label_Category_2 = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_Category_2.setObjectName("label_Category_2")
        self.gridLayout_2.addWidget(self.label_Category_2, 0, 2, 1, 1)
        self.comboBox_Category = QtGui.QComboBox(self.dockWidgetContents_2)
        self.comboBox_Category.setEditable(True)
        self.comboBox_Category.setObjectName("comboBox_Category")
        self.gridLayout_2.addWidget(self.comboBox_Category, 0, 3, 1, 1)
        self.label_Total = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_Total.setObjectName("label_Total")
        self.gridLayout_2.addWidget(self.label_Total, 2, 0, 1, 1)
        self.label_Name = QtGui.QLabel(self.dockWidgetContents_2)
        self.label_Name.setObjectName("label_Name")
        self.gridLayout_2.addWidget(self.label_Name, 0, 0, 1, 1)
        self.doubleSpinBox_Total = QtGui.QDoubleSpinBox(self.dockWidgetContents_2)
        self.doubleSpinBox_Total.setMinimum(-99999999.99)
        self.doubleSpinBox_Total.setMaximum(99999999.99)
        self.doubleSpinBox_Total.setObjectName("doubleSpinBox_Total")
        self.gridLayout_2.addWidget(self.doubleSpinBox_Total, 2, 1, 1, 1)
        self.dockWidget_2.setWidget(self.dockWidgetContents_2)
        self.verticalLayout_2.addWidget(self.dockWidget_2)
        self.dockWidget_3 = QtGui.QDockWidget(self.layoutWidget)
        self.dockWidget_3.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget_3.setObjectName("dockWidget_3")
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setObjectName("dockWidgetContents_3")
        self.dockWidget_3.setWidget(self.dockWidgetContents_3)
        self.verticalLayout_2.addWidget(self.dockWidget_3)
        self.horizontalLayout_2.addWidget(self.mainSplitter)
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1024, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menu_Q = QtGui.QMenu(self.menuBar)
        self.menu_Q.setObjectName("menu_Q")
        mainWindow.setMenuBar(self.menuBar)
        self.toolBar = QtGui.QToolBar(mainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        mainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        self.statusBar.setObjectName("statusBar")
        mainWindow.setStatusBar(self.statusBar)
        self.action_Exit = QtGui.QAction(mainWindow)
        self.action_Exit.setIcon(icon)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Edit = QtGui.QAction(mainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Edit.setIcon(icon1)
        self.action_Edit.setObjectName("action_Edit")
        self.action_Delete = QtGui.QAction(mainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete.setIcon(icon2)
        self.action_Delete.setObjectName("action_Delete")
        self.action_Query = QtGui.QAction(mainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Query.setIcon(icon3)
        self.action_Query.setObjectName("action_Query")
        self.action_Stat = QtGui.QAction(mainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/stat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Stat.setIcon(icon4)
        self.action_Stat.setObjectName("action_Stat")
        self.menuFile.addAction(self.action_Exit)
        self.menu_Q.addAction(self.action_Query)
        self.menu_Q.addAction(self.action_Stat)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menu_Q.menuAction())
        self.toolBar.addAction(self.action_Query)
        self.toolBar.addAction(self.action_Stat)
        self.label.setBuddy(self.dateEdit_From)
        self.label_2.setBuddy(self.dateEdit_To)
        self.label_3.setBuddy(self.comboBox_SearchName)
        self.label_4.setBuddy(self.comboBox_SearchCategory)
        self.label_Date.setBuddy(self.dateEdit_Date)
        self.label_Number.setBuddy(self.doubleSpinBox_OutCome)
        self.label_UnitPrice.setBuddy(self.doubleSpinBox_InCome)
        self.label_Category_2.setBuddy(self.comboBox_Category)
        self.label_Total.setBuddy(self.doubleSpinBox_Total)
        self.label_Name.setBuddy(self.comboBox_Name)

        self.retranslateUi(mainWindow)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL("triggered()"), mainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)
        mainWindow.setTabOrder(self.comboBox_Name, self.comboBox_Category)
        mainWindow.setTabOrder(self.comboBox_Category, self.doubleSpinBox_OutCome)
        mainWindow.setTabOrder(self.doubleSpinBox_OutCome, self.doubleSpinBox_InCome)
        mainWindow.setTabOrder(self.doubleSpinBox_InCome, self.doubleSpinBox_Total)
        mainWindow.setTabOrder(self.doubleSpinBox_Total, self.dateEdit_Date)
        mainWindow.setTabOrder(self.dateEdit_Date, self.tableView)
        mainWindow.setTabOrder(self.tableView, self.buttonBox)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(QtGui.QApplication.translate("mainWindow", "藏龙账务统计", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget.setWindowTitle(QtGui.QApplication.translate("mainWindow", "统计", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("mainWindow", "日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_From.setDisplayFormat(QtGui.QApplication.translate("mainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("mainWindow", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_To.setDisplayFormat(QtGui.QApplication.translate("mainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("mainWindow", "品名：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("mainWindow", "类别：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("mainWindow", "支出：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("mainWindow", "收入：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("mainWindow", "余额：", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_2.setWindowTitle(QtGui.QApplication.translate("mainWindow", "添加", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Date.setText(QtGui.QApplication.translate("mainWindow", "日期(&D)：", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_Date.setDisplayFormat(QtGui.QApplication.translate("mainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Number.setText(QtGui.QApplication.translate("mainWindow", "支出(&U)：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_UnitPrice.setText(QtGui.QApplication.translate("mainWindow", "收入(&I)：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Category_2.setText(QtGui.QApplication.translate("mainWindow", "类别(&C)：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Total.setText(QtGui.QApplication.translate("mainWindow", "余额(&T)：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Name.setText(QtGui.QApplication.translate("mainWindow", "品名(&N)：", None, QtGui.QApplication.UnicodeUTF8))
        self.dockWidget_3.setWindowTitle(QtGui.QApplication.translate("mainWindow", "其他", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("mainWindow", "文件(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_Q.setTitle(QtGui.QApplication.translate("mainWindow", "操作(&O)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("mainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.statusBar.setStatusTip(QtGui.QApplication.translate("mainWindow", "Ready!", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("mainWindow", "退出(&X)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setStatusTip(QtGui.QApplication.translate("mainWindow", "点这个就退出了，快捷键:Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Edit.setText(QtGui.QApplication.translate("mainWindow", "编辑(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Edit.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setText(QtGui.QApplication.translate("mainWindow", "删除(&D)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+Del", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Query.setText(QtGui.QApplication.translate("mainWindow", "查询(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Query.setStatusTip(QtGui.QApplication.translate("mainWindow", "查询并修改记录，快捷键:Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Query.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+F", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stat.setText(QtGui.QApplication.translate("mainWindow", "统计(&S)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stat.setStatusTip(QtGui.QApplication.translate("mainWindow", "对数据进行统计，快捷键:Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Stat.setShortcut(QtGui.QApplication.translate("mainWindow", "Ctrl+S", None, QtGui.QApplication.UnicodeUTF8))

import pygrid_rc
