# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'queryform.ui'
#
# Created: Sat Mar 13 23:24:08 2010
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(854, 644)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/query.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateEdit_From = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_From.setCalendarPopup(True)
        self.dateEdit_From.setObjectName("dateEdit_From")
        self.horizontalLayout.addWidget(self.dateEdit_From)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateEdit_To = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_To.setCalendarPopup(True)
        self.dateEdit_To.setObjectName("dateEdit_To")
        self.horizontalLayout.addWidget(self.dateEdit_To)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_SearchName = QtGui.QComboBox(self.groupBox)
        self.comboBox_SearchName.setEditable(True)
        self.comboBox_SearchName.setObjectName("comboBox_SearchName")
        self.horizontalLayout.addWidget(self.comboBox_SearchName)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_SearchCategory = QtGui.QComboBox(self.groupBox)
        self.comboBox_SearchCategory.setEditable(True)
        self.comboBox_SearchCategory.setObjectName("comboBox_SearchCategory")
        self.horizontalLayout.addWidget(self.comboBox_SearchCategory)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.comboBox_InOutCome = QtGui.QComboBox(self.groupBox)
        self.comboBox_InOutCome.setEditable(True)
        self.comboBox_InOutCome.setObjectName("comboBox_InOutCome")
        self.comboBox_InOutCome.addItem(QtCore.QString())
        self.comboBox_InOutCome.setItemText(0, "")
        self.comboBox_InOutCome.addItem(QtCore.QString())
        self.comboBox_InOutCome.addItem(QtCore.QString())
        self.horizontalLayout.addWidget(self.comboBox_InOutCome)
        self.pushButton_Query = QtGui.QPushButton(self.groupBox)
        self.pushButton_Query.setObjectName("pushButton_Query")
        self.horizontalLayout.addWidget(self.pushButton_Query)
        self.verticalLayout.addWidget(self.groupBox)
        self.tableView = QtGui.QTableView(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.tableView.setFont(font)
        self.tableView.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.tableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tableView.setObjectName("tableView")
        self.verticalLayout.addWidget(self.tableView)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 854, 20))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtGui.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_O = QtGui.QMenu(self.menubar)
        self.menu_O.setObjectName("menu_O")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Exit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Print = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Print.setIcon(icon2)
        self.action_Print.setObjectName("action_Print")
        self.action_Edit = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Edit.setIcon(icon3)
        self.action_Edit.setObjectName("action_Edit")
        self.action_Delete = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Delete.setIcon(icon4)
        self.action_Delete.setObjectName("action_Delete")
        self.menu_F.addAction(self.action_Exit)
        self.menu_O.addAction(self.action_Print)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_O.menuAction())
        self.toolBar.addAction(self.action_Print)
        self.label_2.setBuddy(self.dateEdit_To)
        self.label_3.setBuddy(self.comboBox_SearchName)
        self.label_4.setBuddy(self.comboBox_SearchCategory)
        self.label_5.setBuddy(self.comboBox_SearchCategory)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "管理", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "查询条件", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_From.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_To.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "品名：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "类别：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "支出/收入：", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_InOutCome.setItemText(1, QtGui.QApplication.translate("MainWindow", "支出", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_InOutCome.setItemText(2, QtGui.QApplication.translate("MainWindow", "收入", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Query.setText(QtGui.QApplication.translate("MainWindow", "查询", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Query.setShortcut(QtGui.QApplication.translate("MainWindow", "Return", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_F.setTitle(QtGui.QApplication.translate("MainWindow", "文件(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_O.setTitle(QtGui.QApplication.translate("MainWindow", "操作(&O)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "退出(&X)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setStatusTip(QtGui.QApplication.translate("MainWindow", "点这个就退出了，快捷键:Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setText(QtGui.QApplication.translate("MainWindow", "打印(&P)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setStatusTip(QtGui.QApplication.translate("MainWindow", "将查询结果打印出来，快捷键:Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Edit.setText(QtGui.QApplication.translate("MainWindow", "编辑(&E)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Edit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+E", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setText(QtGui.QApplication.translate("MainWindow", "删除(&D)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Delete.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Del", None, QtGui.QApplication.UnicodeUTF8))

import pygrid_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

