# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'statform.ui'
#
# Created: Sun May 10 10:42:55 2009
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(10)
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/stat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.dateEdit_From = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_From.setCalendarPopup(True)
        self.dateEdit_From.setObjectName("dateEdit_From")
        self.horizontalLayout.addWidget(self.dateEdit_From)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.dateEdit_To = QtGui.QDateEdit(self.groupBox)
        self.dateEdit_To.setCalendarPopup(True)
        self.dateEdit_To.setObjectName("dateEdit_To")
        self.horizontalLayout.addWidget(self.dateEdit_To)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.comboBox_SearchName = QtGui.QComboBox(self.groupBox)
        self.comboBox_SearchName.setEditable(True)
        self.comboBox_SearchName.setObjectName("comboBox_SearchName")
        self.horizontalLayout.addWidget(self.comboBox_SearchName)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.comboBox_SearchCategory = QtGui.QComboBox(self.groupBox)
        self.comboBox_SearchCategory.setEditable(True)
        self.comboBox_SearchCategory.setObjectName("comboBox_SearchCategory")
        self.horizontalLayout.addWidget(self.comboBox_SearchCategory)
        self.pushButton_Stat = QtGui.QPushButton(self.groupBox)
        self.pushButton_Stat.setObjectName("pushButton_Stat")
        self.horizontalLayout.addWidget(self.pushButton_Stat)
        self.verticalLayout.addWidget(self.groupBox)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtGui.QWidget()
        self.tab.setObjectName("tab")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.tableWidget_OverView = QtGui.QTableWidget(self.tab)
        self.tableWidget_OverView.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_OverView.setObjectName("tableWidget_OverView")
        self.tableWidget_OverView.setColumnCount(3)
        self.tableWidget_OverView.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_OverView.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_OverView.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_OverView.setHorizontalHeaderItem(2, item)
        self.horizontalLayout_2.addWidget(self.tableWidget_OverView)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.tab_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.tableWidget_NameGroup = QtGui.QTableWidget(self.tab_2)
        self.tableWidget_NameGroup.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_NameGroup.setObjectName("tableWidget_NameGroup")
        self.tableWidget_NameGroup.setColumnCount(4)
        self.tableWidget_NameGroup.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_NameGroup.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_NameGroup.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_NameGroup.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_NameGroup.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_3.addWidget(self.tableWidget_NameGroup)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.tab_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.tableWidget_CategoryGroup = QtGui.QTableWidget(self.tab_3)
        self.tableWidget_CategoryGroup.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_CategoryGroup.setObjectName("tableWidget_CategoryGroup")
        self.tableWidget_CategoryGroup.setColumnCount(4)
        self.tableWidget_CategoryGroup.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_CategoryGroup.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_CategoryGroup.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_CategoryGroup.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_CategoryGroup.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_4.addWidget(self.tableWidget_CategoryGroup)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.tab_4)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.tableWidget_MonthGroup = QtGui.QTableWidget(self.tab_4)
        self.tableWidget_MonthGroup.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_MonthGroup.setObjectName("tableWidget_MonthGroup")
        self.tableWidget_MonthGroup.setColumnCount(4)
        self.tableWidget_MonthGroup.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MonthGroup.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MonthGroup.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MonthGroup.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_MonthGroup.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_5.addWidget(self.tableWidget_MonthGroup)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.tab_5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.tableWidget_YearGroup = QtGui.QTableWidget(self.tab_5)
        self.tableWidget_YearGroup.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.tableWidget_YearGroup.setObjectName("tableWidget_YearGroup")
        self.tableWidget_YearGroup.setColumnCount(4)
        self.tableWidget_YearGroup.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_YearGroup.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_YearGroup.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_YearGroup.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget_YearGroup.setHorizontalHeaderItem(3, item)
        self.horizontalLayout_6.addWidget(self.tableWidget_YearGroup)
        self.tabWidget.addTab(self.tab_5, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menu_F = QtGui.QMenu(self.menubar)
        self.menu_F.setObjectName("menu_F")
        self.menu_O = QtGui.QMenu(self.menubar)
        self.menu_O.setObjectName("menu_O")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_Exit = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/exit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Exit.setIcon(icon1)
        self.action_Exit.setObjectName("action_Exit")
        self.action_Print = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/print.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_Print.setIcon(icon2)
        self.action_Print.setObjectName("action_Print")
        self.menu_F.addAction(self.action_Exit)
        self.menu_O.addAction(self.action_Print)
        self.menubar.addAction(self.menu_F.menuAction())
        self.menubar.addAction(self.menu_O.menuAction())
        self.toolBar.addAction(self.action_Print)
        self.label.setBuddy(self.dateEdit_From)
        self.label_2.setBuddy(self.dateEdit_To)
        self.label_3.setBuddy(self.comboBox_SearchName)
        self.label_4.setBuddy(self.comboBox_SearchCategory)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.action_Exit, QtCore.SIGNAL("activated()"), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "统计", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "设置筛选条件", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "日期：", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_From.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "至", None, QtGui.QApplication.UnicodeUTF8))
        self.dateEdit_To.setDisplayFormat(QtGui.QApplication.translate("MainWindow", "yyyy-MM-dd", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "品名：", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "类别：", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Stat.setText(QtGui.QApplication.translate("MainWindow", "统计", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_OverView.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "支出", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_OverView.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "收入", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_OverView.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "余额", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("MainWindow", "总体统计", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_NameGroup.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "品名", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_NameGroup.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "支出", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_NameGroup.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "收入", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_NameGroup.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "余额", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("MainWindow", "按品名分组", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_CategoryGroup.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "类别", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_CategoryGroup.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "支出", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_CategoryGroup.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "收入", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_CategoryGroup.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "余额", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("MainWindow", "按类别分组", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_MonthGroup.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "月份", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_MonthGroup.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "支出", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_MonthGroup.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "收入", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_MonthGroup.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "余额", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("MainWindow", "按月分组", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_YearGroup.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "年份", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_YearGroup.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "支出", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_YearGroup.horizontalHeaderItem(2).setText(QtGui.QApplication.translate("MainWindow", "收入", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget_YearGroup.horizontalHeaderItem(3).setText(QtGui.QApplication.translate("MainWindow", "余额", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QtGui.QApplication.translate("MainWindow", "按年分组", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_F.setTitle(QtGui.QApplication.translate("MainWindow", "文件(&F)", None, QtGui.QApplication.UnicodeUTF8))
        self.menu_O.setTitle(QtGui.QApplication.translate("MainWindow", "操作(&O)", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setText(QtGui.QApplication.translate("MainWindow", "退出(&X)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setStatusTip(QtGui.QApplication.translate("MainWindow", "点这个就退出了，快捷键:Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Exit.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setText(QtGui.QApplication.translate("MainWindow", "打印(&P)", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setStatusTip(QtGui.QApplication.translate("MainWindow", "把统计的结果打印出来，快捷键:Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))
        self.action_Print.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+P", None, QtGui.QApplication.UnicodeUTF8))

import pygrid_rc
